FROM node:20-bullseye

WORKDIR /app

COPY Server/src ./src
COPY Server/package*.json ./
COPY Server/babel.config.js ./
COPY Server/.babelignore ./
COPY Server/tsconfig.json ./

RUN npm ci

COPY Server/framework-express ./framework-express
WORKDIR /app/framework-express
RUN npm ci

WORKDIR /app
RUN npm run build
EXPOSE 3000

ENV HOST=localhost
ENV PORT=5432
ENV DATABASE_NAME=anekdot_test
ENV USER=postgres
ENV PASSWORD=password

WORKDIR /app/framework-express
CMD ["node", "index.js"]