version: '3.8'
services:
  test-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: anekdot_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

