# deploy-allure.yml
name: Deploy Allure Report to Pages

on:
  workflow_run:
    workflows: ["Node.js Tests in Docker Container"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download test artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const runId = context.payload.workflow_run.id;
            
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner,
              repo,
              run_id: runId,
            });
            
            const testArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === "test-results"
            );
            
            if (testArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner,
                repo,
                artifact_id: testArtifact.id,
                archive_format: 'zip',
              });
            
              const fs = require('fs');
              fs.writeFileSync('${{github.workspace}}/test-results.zip', Buffer.from(download.data));
              console.log('✅ Artifact downloaded successfully');
            } else {
              console.log('❌ No test-results artifact found');
              throw new Error('No test-results artifact found');
            }

      - name: Unzip artifacts
        run: |
          unzip -q test-results.zip -d extracted-results || echo "No zip file found"
          echo "=== Extracted contents ==="
          find extracted-results -type f -name "*.json" | head -5
          find extracted-results -name "allure-report" -type d
          find extracted-results -name "allure-history" -type d

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Allure
        run: |
          npm install -g allure-commandline

      - name: Generate Allure HTML Report with history
        run: |
          mkdir -p allure-report
          mkdir -p allure-history
          
          # Копируем историю из предыдущих запусков если есть
          if [ -d "extracted-results/allure-history" ]; then
            echo "Found previous allure history"
            cp -r extracted-results/allure-history/. allure-history/
          fi
          
          # Генерируем новый отчет
          if [ -d "extracted-results/test-results" ]; then
            echo "Generating report from test-results"
            allure generate extracted-results/test-results -o allure-report --clean --history-dir allure-history
          elif [ -d "extracted-results/allure-results" ]; then
            echo "Generating report from allure-results"
            allure generate extracted-results/allure-results -o allure-report --clean --history-dir allure-history
          else
            echo "❌ No test results found"
            find extracted-results -type d
            exit 1
          fi
          
          # Сохраняем историю для следующего запуска
          cp -r allure-history/. allure-report/history/ || echo "No history to copy"
          
          echo "=== Allure report contents ==="
          ls -la allure-report/
          echo "=== History contents ==="
          ls -la allure-report/history/ 2>/dev/null || echo "No history directory"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4