name: Node.js Tests in Docker Container

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test container
        run: |
          docker build -f Dockerfile.test -t my-tests .

      - name: Run tests in container
        run: |
          docker run --rm \
            -e JWT_SECRET="test_jwt_secret_for_testing" \
            -e NODE_ENV="test" \
            -v "$(pwd)/test-results:/app/allure-results" \
            my-tests

      - name: Generate Allure HTML Report
        run: |
          npm install -g allure-commandline
          allure generate test-results -o allure-report --clean

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            allure-report/
            test-results/
          retention-days: 30