name: Node.js Tests in Docker Container

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: anekdot_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test container
        run: |
          docker build -f Dockerfile.test -t my-tests .

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Initialize test database
        run: |
          # Используем тот же код что и в тестах!
          docker run --rm \
            --network host \
            my-tests \
            sh -c "npm run test:db:init"

      - name: Run unit tests
        id: unit-tests
        run: |
          docker run --rm \
            --network host \
            -v "$(pwd)/test-results:/app/allure-results" \
            -v "$(pwd)/allure-history:/app/allure-history" \
            my-tests \
            sh -c "npm run test"

      - name: Run integration tests
        id: integration-tests
        if: steps.unit-tests.outcome == 'success'
        run: |
          docker run --rm \
            --network host \
            -v "$(pwd)/test-results:/app/allure-results" \
            -v "$(pwd)/allure-history:/app/allure-history" \
            my-tests \
            sh -c "npm run test:integration"

      - name: Download previous allure history
        uses: actions/cache@v4
        with:
          path: allure-history
          key: allure-history-${{ github.ref }}
          restore-keys: |
            allure-history-

      - name: Generate Allure HTML Report with history
        if: always()
        run: |
          npm install -g allure-commandline
          
          # Создаем директорию для истории если её нет
          mkdir -p allure-history
          
          # Генерируем отчет с историей
          allure generate test-results -o allure-report --clean --history-dir allure-history
          
          # Копируем историю в отчет для следующего запуска
          cp -r allure-history/. allure-report/history/ || echo "No history to copy"

      - name: Save allure history
        uses: actions/cache@v4
        with:
          path: allure-history
          key: allure-history-${{ github.ref }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            allure-report/
            test-results/
            allure-history/
          retention-days: 30