name: Node.js Tests in Docker Compose

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml run --rm tests

      - name: Generate Allure HTML Report
        run: |
          npm install -g allure-commandline
          allure generate test-results -o allure-report --clean

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            allure-report/
            test-results/
          retention-days: 30

      - name: Cleanup
        run: |
          docker compose -f docker-compose.test.yml down